sudo: false
os:
    - linux
    - osx
language: node_js
node_js:
    - 8
    - 9
    - 10
    - 11
cache:
    directories:
        - node_modules
        - "$HOME/.npm"

before_script:
    - npm prune

script:
    - npm run lint
    - npm run test-cov

after_script:
    - npm install codecov
    - ./node_modules/.bin/codecov
